//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnvioMailsProdeo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mails
    {
        public int idMail { get; set; }
        public Nullable<int> idProyecto { get; set; }
        public Nullable<int> idModulo { get; set; }
        public Nullable<int> idTarea { get; set; }
        public string asunto { get; set; }
        public string detalle { get; set; }
        public string destinatarios { get; set; }
        public string enviado { get; set; }
    }
}
