//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnvioMailsProdeo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prodeoEntities : DbContext
    {
        public prodeoEntities()
            : base("name=prodeoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Modulos> Modulos { get; set; }
        public virtual DbSet<Participantes> Participantes { get; set; }
        public virtual DbSet<ParticipantesProyectos> ParticipantesProyectos { get; set; }
        public virtual DbSet<ParticipantesTareas> ParticipantesTareas { get; set; }
        public virtual DbSet<Proyectos> Proyectos { get; set; }
        public virtual DbSet<Tareas> Tareas { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Mails> Mails { get; set; }
    }
}
