//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnvioMailsProdeo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantesProyectos
    {
        public int id { get; set; }
        public int idUsuario { get; set; }
        public int idProyecto { get; set; }
        public string permisosAdministrador { get; set; }
    
        public virtual Proyectos Proyectos { get; set; }
    }
}
