//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnvioMailsProdeo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantesTareas
    {
        public int idUsuario { get; set; }
        public int idTarea { get; set; }
        public int id { get; set; }
    
        public virtual Tareas Tareas { get; set; }
    }
}
