//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnvioMailsProdeo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyectos
    {
        public Proyectos()
        {
            this.Modulos = new HashSet<Modulos>();
            this.ParticipantesProyectos = new HashSet<ParticipantesProyectos>();
        }
    
        public int idProyecto { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public Nullable<System.DateTime> FechaFinalizacion { get; set; }
        public string AlertaPrevia { get; set; }
    
        public virtual ICollection<Modulos> Modulos { get; set; }
        public virtual ICollection<ParticipantesProyectos> ParticipantesProyectos { get; set; }
    }
}
